"use client"
import { useState } from "react"
import { Activity, ArrowRight, Bike, Check, Dumbbell, Flame, HeartPulse, Home, Sparkles, Target, Trophy } from "lucide-react"
import { Badge, Button, Card } from "@/components/ui"
import Link from "next/link"
const goals=[[Flame,"Lose Weight","Burn fat, feel lighter"],[Dumbbell,"Build Muscle","Strength and definition"],[Bike,"Endurance","Go farther, feel fitter"],[HeartPulse,"Stay Active","Move well, live well"]]
export default function Onboarding(){const [step,setStep]=useState(1); return <main className="mesh min-h-screen px-5 py-8"><div className="mx-auto max-w-3xl"><div className="flex items-center justify-between"><Link href="/" className="flex gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#008b8b] text-[#effffe]"><Dumbbell size={19}/></span><span className="display text-lg font-bold">FITNESS <b className="text-[#008b8b]">SAARTHI</b></span></Link><p className="text-xs text-[#8b9691]">STEP {step} OF 5</p></div><div className="mt-7 h-1 rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-[#008b8b] transition-all" style={{width:`${step*20}%`}}/></div>
<div className="mt-12 text-center"><Badge>Let's know you better</Badge><h1 className="display mt-4 text-4xl font-bold uppercase">{step===1?"What is your main goal?":step===2?"Tell us your numbers":step===3?"How active are you?":step===4?"Where do you train?":"Your plan is ready!"}</h1><p className="mt-2 text-sm text-[#8b9691]">{step===5?"Your AI-powered journey has been tailored to you.":"This helps Saarthi create a plan that fits your life."}</p></div>
<Card className="mx-auto mt-9 max-w-2xl p-6">{step===1&&<div className="grid gap-3 sm:grid-cols-2">{goals.map(([Icon,t,s]:any)=><button key={t} className="flex gap-4 rounded-2xl border border-white/[.07] bg-white/[.025] p-4 text-left transition hover:border-[#008b8b]/50 hover:bg-[#008b8b]/[.05]"><span className="grid size-11 place-items-center rounded-xl bg-[#008b8b]/10 text-[#008b8b]"><Icon/></span><span><b>{t}</b><small className="mt-1 block text-[#8b9691]">{s}</small></span></button>)}</div>}
{step===2&&<div className="grid gap-4 sm:grid-cols-3">{["Age","Height (cm)","Weight (kg)"].map((x,i)=><label key={x}><span className="mb-2 block text-xs text-[#8b9691]">{x}</span><input defaultValue={[28,175,78][i]} className="w-full rounded-xl border border-white/[.07] bg-black/20 p-4 text-xl font-bold"/></label>)}</div>}
{step===3&&<div className="space-y-3">{["Mostly sedentary","Lightly active","Active most days","Very active"].map((x,i)=><button key={x} className={`flex w-full items-center justify-between rounded-xl border p-4 text-left text-sm font-bold ${i===2?"border-[#008b8b]/50 bg-[#008b8b]/[.06]":"border-white/[.07]"}`}>{x}{i===2&&<Check className="text-[#008b8b]" size={17}/>}</button>)}</div>}
{step===4&&<div className="grid grid-cols-2 gap-3">{[[Home,"Home"],[Dumbbell,"Gym"],[Activity,"Outdoors"],[Target,"Minimal gear"]].map(([Icon,t]:any)=><button key={t} className="grid place-items-center gap-2 rounded-xl border border-white/[.07] p-5 text-sm font-bold hover:border-[#008b8b]/50"><Icon className="text-[#008b8b]"/>{t}</button>)}</div>}
{step===5&&<div className="text-center"><span className="pulse-glow mx-auto grid size-20 place-items-center rounded-full bg-[#008b8b] text-[#effffe]"><Sparkles size={34}/></span><h3 className="mt-6 display text-3xl font-bold">STRONG START PLAN</h3><p className="mt-2 text-sm text-[#8b9691]">4 workouts • 45 min average • Strength focus</p><Link href="/dashboard"><Button className="mt-7">Enter your dashboard <ArrowRight size={17}/></Button></Link></div>}
{step<5&&<Button onClick={()=>setStep(step+1)} className="mt-7 w-full">Continue <ArrowRight size={17}/></Button>}</Card></div></main>}
