import Link from "next/link"
import { Activity, ArrowRight, Bot, Check, ChevronRight, Dumbbell, Flame, HeartPulse, Play, Sparkles, Star, Trophy, Users } from "lucide-react"
import { Badge, Button, Card } from "@/components/ui"

export default function Landing(){
 const features=[[Bot,"AI Coach","Plans that understand your body, routine, and favourite Indian foods."],[Dumbbell,"Smart Workouts","From home workouts to gym splits, every rep has a purpose."],[Activity,"Real Progress","Track strength, nutrition, streaks and transformations in one place."]]
 return <div className="mesh grid-bg min-h-screen overflow-hidden">
  <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#008b8b] text-[#effffe]"><Dumbbell/></span><span className="display text-xl font-bold leading-4">FITNESS<br/><b className="text-[#008b8b]">SAARTHI</b></span></div><nav className="hidden gap-8 text-sm text-[#a4adaa] md:flex"><a href="#features">Features</a><a href="#how">How it works</a><a href="#pricing">Pricing</a></nav><Link href="/login"><Button variant="soft">Log in <ChevronRight size={15}/></Button></Link></header>
  <main>
   <section className="relative mx-auto grid min-h-[760px] max-w-7xl items-center gap-10 px-5 pb-20 pt-16 lg:grid-cols-[1.1fr_.9fr] lg:pt-8">
    <div><Badge>Your AI powered fitness companion</Badge><h1 className="display mt-6 max-w-3xl text-6xl font-bold uppercase leading-[.92] md:text-8xl">Stronger every day. <span className="text-gradient">Together.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-[#9ba5a1]">Your personal fitness saarthi, built for Indian lives. Get expert workouts, smarter nutrition, and daily motivation that adapts with you.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/onboarding"><Button className="px-7">Apni journey shuru karo <ArrowRight size={17}/></Button></Link><Button variant="ghost"><span className="grid size-8 place-items-center rounded-full border border-white/15"><Play size={13}/></span> See how it works</Button></div><div className="mt-12 flex flex-wrap gap-7 text-xs text-[#929d99]"><span className="flex gap-2"><Check size={15} className="text-[#008b8b]"/> No credit card</span><span className="flex gap-2"><Check size={15} className="text-[#008b8b]"/> 7-day free trial</span><span className="flex gap-2"><Check size={15} className="text-[#008b8b]"/> Cancel anytime</span></div></div>
    <div className="relative mx-auto w-full max-w-[530px]"><div className="absolute -inset-16 rounded-full bg-[#008b8b]/10 blur-[100px]"/><Card className="relative p-5"><div className="flex items-center justify-between"><div><p className="text-xs text-[#8b9691]">Today&apos;s workout</p><h3 className="mt-1 text-2xl font-bold">Upper Body Power</h3></div><span className="grid size-11 place-items-center rounded-xl bg-[#008b8b] text-[#effffe]"><Play size={17} fill="currentColor"/></span></div><div className="mt-6 h-44 rounded-2xl bg-[linear-gradient(120deg,rgba(0,139,139,.15),rgba(0,0,0,.4)),url('https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80')] bg-cover bg-center"/><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div><p className="display text-2xl font-bold text-[#008b8b]">45</p><p className="text-[10px] text-[#8b9691]">MINUTES</p></div><div><p className="display text-2xl font-bold">6</p><p className="text-[10px] text-[#8b9691]">EXERCISES</p></div><div><p className="display text-2xl font-bold">320</p><p className="text-[10px] text-[#8b9691]">KCAL</p></div></div></Card><Card glass className="absolute -left-12 top-28 hidden w-36 p-4 lg:block"><Flame className="text-[#ff6b35]"/><p className="mt-2 display text-3xl font-bold">12</p><p className="text-[10px] text-[#8b9691]">DAY STREAK</p></Card><Card glass className="absolute -right-8 -top-6 hidden w-44 p-4 lg:block"><div className="flex items-center gap-2"><Sparkles className="text-[#008b8b]" size={18}/><p className="text-xs font-bold">AI Plan ready</p></div><p className="mt-2 text-[10px] leading-4 text-[#8b9691]">Optimized for your goals</p></Card></div>
   </section>
   <section id="features" className="mx-auto max-w-7xl px-5 py-20"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#008b8b]">Made for your journey</p><h2 className="display mt-3 text-5xl font-bold uppercase">Your fitness. <span className="text-[#008b8b]">Upgraded.</span></h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{features.map(([Icon,title,text]:any)=><Card key={title} className="p-7"><span className="grid size-12 place-items-center rounded-2xl bg-[#008b8b]/10 text-[#008b8b]"><Icon/></span><h3 className="mt-7 text-2xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#8b9691]">{text}</p></Card>)}</div></section>
   <section id="pricing" className="mx-auto max-w-3xl px-5 py-20 text-center"><Badge>Simple pricing</Badge><h2 className="display mt-4 text-5xl font-bold uppercase">Invest in your <span className="text-[#008b8b]">best self.</span></h2><Card className="mx-auto mt-10 max-w-md p-8 text-left"><div className="flex justify-between"><div><p className="font-bold">Saarthi Pro</p><p className="mt-2 text-xs text-[#8b9691]">Everything you need to transform.</p></div><p className="display text-4xl font-bold">₹499<span className="text-sm text-[#8b9691]">/mo</span></p></div><div className="my-6 h-px bg-white/[.06]"/>{["Unlimited AI coaching","Personalized workout plans","Nutrition and progress tracking","Community challenges"].map(x=><p key={x} className="mb-3 flex gap-3 text-sm"><Check size={16} className="text-[#008b8b]"/>{x}</p>)}<Link href="/onboarding"><Button className="mt-4 w-full">Start free for 7 days</Button></Link></Card></section>
  </main><footer className="border-t border-white/[.05] px-5 py-7 text-center text-xs text-[#68736f]">Built with strength in India. Fitness Saarthi © 2026</footer>
 </div>
}
