"use client"
import Link from "next/link"
import { ArrowRight, Dumbbell, LockKeyhole, Mail, UserRound } from "lucide-react"
import { Button, Card } from "@/components/ui"

export default function Register(){
  function rememberName(value:string){localStorage.setItem("fitness-saarthi-user-name",value.trim())}
  return <main className="mesh grid min-h-screen place-items-center px-5 py-10"><div className="w-full max-w-md"><Link href="/" className="mb-8 flex justify-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#008b8b] text-[#effffe]"><Dumbbell/></span><span className="display text-xl font-bold leading-4">FITNESS<br/><b className="text-[#008b8b]">SAARTHI</b></span></Link><Card className="p-7"><h1 className="display text-3xl font-bold">Join the movement</h1><p className="mt-1 text-sm text-[#8b9691]">Let&apos;s build your personalized plan.</p><div className="mt-7 space-y-3"><label className="hover-lift flex items-center gap-3 rounded-xl border border-white/[.07] bg-black/20 px-4 py-3"><UserRound size={16} className="text-[#008b8b]"/><input onChange={e=>rememberName(e.target.value)} className="w-full bg-transparent text-sm" placeholder="Your full name"/></label><label className="hover-lift flex items-center gap-3 rounded-xl border border-white/[.07] bg-black/20 px-4 py-3"><Mail size={16} className="text-[#008b8b]"/><input className="w-full bg-transparent text-sm" placeholder="Email address"/></label><label className="hover-lift flex items-center gap-3 rounded-xl border border-white/[.07] bg-black/20 px-4 py-3"><LockKeyhole size={16} className="text-[#008b8b]"/><input type="password" className="w-full bg-transparent text-sm" placeholder="Create password"/></label></div><Link href="/onboarding"><Button className="mt-6 w-full">Create account <ArrowRight size={16}/></Button></Link><p className="mt-5 text-center text-xs text-[#8b9691]">Already a member? <Link href="/login" className="font-bold text-[#008b8b]">Log in</Link></p></Card></div></main>
}
