import AppShell from "@/components/app-shell"
import { Badge, Button, Card, SectionTitle } from "@/components/ui"
import { Clock3, Dumbbell, Filter, Flame, Play, Search, SlidersHorizontal, Sparkles, Zap } from "lucide-react"
import Link from "next/link"
const workouts=[
 ["Upper Body Power","Chest • Shoulders • Triceps","45 min","Intermediate","https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80"],
 ["Full Body Burn","Strength • Cardio • Core","35 min","Advanced","https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=80"],
 ["Morning Mobility","Flexibility • Recovery","20 min","Beginner","https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80"],
 ["Leg Day Builder","Quads • Glutes • Hamstrings","50 min","Intermediate","https://images.unsplash.com/photo-1434682881908-b43d0467b798?auto=format&fit=crop&w=800&q=80"],
 ["Core Crusher","Abs • Obliques • Stability","25 min","Advanced","https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=800&q=80"],
 ["Home HIIT Express","Cardio • Bodyweight","18 min","Beginner","https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=800&q=80"],
]
export default function Workouts(){return <AppShell><div className="mx-auto max-w-[1500px]"><div className="flex flex-wrap justify-between gap-4"><div><h1 className="display text-4xl font-bold">Workout <span className="text-[#008b8b]">Library</span></h1><p className="mt-1 text-sm text-[#8b9691]">Train your way. Every workout is built to move you forward.</p></div><Button><Sparkles size={16}/> Generate with AI</Button></div><div className="mt-7 flex flex-wrap gap-3"><label className="flex min-w-56 flex-1 items-center gap-3 rounded-xl border border-white/[.07] bg-white/[.03] px-4"><Search size={17} className="text-[#8b9691]"/><input className="w-full bg-transparent py-3 text-sm" placeholder="Search workouts..."/></label>{["All","Strength","Cardio","Yoga","At home"].map((x,i)=><button key={x} className={`rounded-xl border px-4 text-xs font-bold ${i===0?"border-[#008b8b] bg-[#008b8b] text-[#effffe]":"border-white/[.07] text-[#8b9691]"}`}>{x}</button>)}<button className="grid size-11 place-items-center rounded-xl border border-white/[.07]"><SlidersHorizontal size={17}/></button></div><section className="mt-9"><SectionTitle eyebrow="Recommended for you" title="Find Your Next Challenge"/><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{workouts.map(([title,tags,time,level,img],i)=><Card key={title} className="overflow-hidden"><div className="relative h-44 bg-cover bg-center" style={{backgroundImage:`linear-gradient(0deg,rgba(10,12,11,.8),transparent),url(${img})`}}><div className="absolute left-4 top-4">{i===0?<Badge>AI pick</Badge>:<Badge orange={level==="Advanced"}>{level}</Badge>}</div><Link href={i===0?"/workouts/active":"/workouts/active"} className="absolute bottom-4 right-4 grid size-10 place-items-center rounded-full bg-[#008b8b] text-[#effffe]"><Play fill="currentColor" size={15}/></Link></div><div className="p-5"><h3 className="display text-2xl font-bold">{title}</h3><p className="mt-1 text-[11px] uppercase tracking-wider text-[#8b9691]">{tags}</p><div className="mt-4 flex gap-4 text-xs text-[#a5afab]"><span className="flex gap-1"><Clock3 size={14}/>{time}</span><span className="flex gap-1"><Flame size={14} className="text-[#ff6b35]"/>{220+i*35} kcal</span></div></div></Card>)}</div></section></div></AppShell>}
